FORMAT: 1A
HOST: https://useraddlist.apiblueprint.org/ethinkers-frontend

# useraddlist

Mockup for adding and listing users.

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "users": [
                    {
                        "firstname":"Usuário 1"
                        "lastname":"Sobrenome 1"
                        "cpf":04080757247
                        "phone":11987654321
                        "email":"myemail1@test.com.br"
                        "id":1
                    },
                    {
                        "firstname":"Usuário 2"
                        "lastname":"Sobrenome 2"
                        "cpf":04080757247
                        "phone":11987654321
                        "email":"myemail2@test.com.br"
                        "id":2
                    },
                    {
                        "firstname":"Usuário 3"
                        "lastname":"Sobrenome 3"
                        "cpf":04080757247
                        "phone":11987654321
                        "email":"myemail3@test.com.br"
                        "id":3
                    },
                    {
                        "firstname":"Usuário 4"
                        "lastname":"Sobrenome 4"
                        "cpf":04080757247
                        "phone":11987654321
                        "email":"myemail4@test.com.br"
                        "id":4
                    },
                   {
                        "firstname":"Usuário 5"
                        "lastname":"Sobrenome 5"
                        "cpf":04080757247
                        "phone":11987654321
                        "email":"myemail5@test.com.br"
                        "id":5
                    },
                ]
            }
        ]

### Create a New User [POST]

You may create your own user using this action.

+ Request (application/json)

        {
            "firstname":"Usuário 7"
            "lastname":"Sobrenome 7"
            "cpf":04080757247
            "phone":11987654321
            "email":"myemail7@test.com.br"
            "id":7
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/add

    + Body

            {
                "firstname":"Usuário 7"
                "lastname":"Sobrenome 7"
                "cpf":04080757247
                "phone":11987654321
                "email":"myemail7@test.com.br"
                "id":7
            }